apiVersion: v1
kind: ConfigMap

metadata:
  name: server-conf
  namespace: web

data:
  server.conf: |
    server {
        listen 80;
        listen [::]:80;
        server_name localhost;

        error_page 500 502 503 504 /50x.html;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
